print(" ****************************** ")
print(" **  El Programa de Chistes  ** ")
print(' ****************************** ')
print('                                ')
input()
print(' ¿Qué sale de la cruza de un mono y un pato? ')
input()
print(' ¡Un Monopatin! ')
input()
print(' ¿Porqué vuelan los pajaros pa\'l sur ? ')
input()
print(" ¡Porque caminando tardarian muchisimo! ")
print(" JA JA JA")
input()
print(" ¿En qué se parece una familia, un bombero y un barco?")
input()
print(" No sé, ¿en que se parecen?")
input()
print(" En que el bombero y el barco tienen casco.")
input()
print(" ¿Y la familia ? ", end="" )
print(" Bien gracias ", end="")
print(" Bien gracias ", end="")
input()

